sudo: required
dist: trusty
language: node_js
node_js:
  - node
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g angular-cli@1.0.0-beta.17
  - npm install -g karma
  - npm install
  - ng build
script:
  - karma start karma.conf.js --single-run
after_success:
  - bash deploy.sh
env:
  global:
    secure: VT1Qnl1EFFBaI+NPwTNqaMBTWpO+TI70RT2ptLpcAHGPQjKRRLdmG1b2Rgt6pbhN/KqjwLnxWqqNSfuzby6AKebN6W/8G6g9zZeLrwpgA9XcTigqXMuRh5ysEgcOqhkydrIqe1OI1Y4iH+H7Ah4DRv56UOELYhhZ1HwtfbyEFIHf9taA2I80aoo+tHDtXFdSNYDxIAJ+R4zauM0zoLBQSJkPoyCXgCKOzW9NRrO/AlCq+A/3xSq3XTTxCO85q1AQAAYZAs+80ZGjPV+UQ8vconsR1wZgG79IrWv/uLtmt+fEU6xaXxhXaK0qnJEVthXvXW85foOd85wF1pL71XNr/xjMkLazjmmOjG7szeUABaUnsFgSNII5BBedl26KLGjkoCzTe32CaTyrwsM6TdYqncoBwT+9PwCefspG8Rb7DAzq4IUdLrWiRNI8K+LwUTeFV7PXFgN8HToZqGLPpeB5RVTU3hdOrRrAOhzv7MGlmZRSD2xDjh9WctCvCiEXNCInUbCBXrkroIw/4VahQD3VvXgT03klPZDpdpFAZBSufmSMPI5z0UTSIN0VEhzgXgPGZWWe3pNOg9xtQhjAZhHc22APRIMazIT8NC/1RrLbRUSogVDsRYwatjhmF61v08J45eb1rrFkzyzCJAs/SJ1OLm+mCxOobM1Hpsoc59vCH9c=
